house_map:
  #reference coordinate frame
  frame_id: "map"
  locations:
    # room locations
    office_room:
      name: "office room"
      position: [-6.348, 3.131] # [x,y]
      orientation: [0.0, 0.0, 0.0] # [roll,pitch,yaw]

    living_room:
      name: "living room"
      position: [-3.088,1.015]
      orientation: [0.0, 0.0, 0.0]

    foyer: 
      name: "foyer"    
      position: [1.034,0.243]
      orientation: [0.0, 0.0, 0.0]

    dining_room: 
      name: "dining room"       
      position: [4.659,1.289]
      orientation: [0.0, 0.0, 0.0]

    toilet: 
      name: "toilet"     
      position: [1.001,2.995]
      orientation: [0.0, 0.0, 0.0]

    bedroom: 
      name: "bedroom"
      position: [5.796,-4.342]
      orientation: [0.0, 0.0, 0.0]
      
  areas:
    office_room: 
      name: "office room"
      area: 
        x: [-7.347, -5.406] # [x_min,x_max]
        y: [-3.86, 5.356] # [y_min,y_max]

    living_room: 
      name: "living room"
      area:
        x: [-5.029, -0.182 ]
        y: [-0.131, 5.313 ] 

    foyer: 
      name: "foyer"
      area:
        x: [-0.095 , 2.174]
        y: [-0.135 , 0.856]          

    dining_room: 
      name: "dining room"
      area: 
        x: [2.264 , 7.265]
        y: [-0.301 , 5.069]         

    toilet: 
      name: "toilet"
      area:
        x: [-0.015 , 2.184]
        y: [0.852 , 5.149]         

    bedroom: 
      name: "bedroom"
      area:
        x: [4.774 , 7.137]
        y: [-5.448 , -0.465]  
